name: Laravel CI

on:
  push:
  pull_reauest:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          tools: composer:v2

      - name: check php version
        run: php -v

      - name: check composer version
        run: composer --version

      - name: install php dependencies
        run: composer install --no-interaction --prefer-dist

      - name: prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: run tests
        run: php artisan test



