name: First Workflow

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        uses: actions/checkout@v4
      - name: Hello World
        run: echo "Hello World"
      - name: show files
        run: ls
